#!/bin/zsh

assertCommandExists() {
  which $1 > /dev/null 2>&1
  CMD_NOT_FOUND=$?
  if [[ $CMD_NOT_FOUND -ne 0 ]]; then
    echo FAILURE: Could not find $1 command on the PATH
    exit $CMD_NOT_FOUND
  fi
}

assertCommandExists git
assertCommandExists bundle

git pull --no-edit dev master
git push origin sources

bundle exec jekyll serve --config _config-dev.yml -D
